version: "3.8"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - mydockernetwork
    depends_on:
      - restapi

  restapi:
    build: ./restapi
    ports:
      - "8080:8080"
    networks:
      - mydockernetwork
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: ShamilPass123
      MYSQL_DATABASE: shamil-database-arbeidskrav
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mydockernetwork
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pShamilPass123"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  mydockernetwork:
    driver: bridge

volumes:
  mysql_data:
